name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-push:
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Build Docker image
      - name: Build Docker image
        run: docker build -t ghcr.io/aniolmg/titanic-ml-api:latest .

      # 4. Tag image with commit SHA
      - name: Tag image
        run: |
          IMAGE_TAG=ghcr.io/aniolmg/titanic-ml-api:${{ github.sha }}
          docker tag ghcr.io/aniolmg/titanic-ml-api:latest $IMAGE_TAG

      # 5. Push images
      - name: Push Docker image
        run: |
          docker push ghcr.io/aniolmg/titanic-ml-api:latest
          docker push ghcr.io/aniolmg/titanic-ml-api:${{ github.sha }}
